---
- name: "Approved"
  color: "f7e101"
  description: ""
- name: "Changes Done"
  color: "f7e101"
  description: ""
- name: "Changes Requested"
  color: "f7e101"
  description: ""
- name: "Comment Added"
  color: "f7e101"
  description: ""
- name: "Comments Addressed"
  color: "f7e101"
  description: ""
- name: "Core"
  color: "f7e101"
  description: ""
- name: "dependencies"
  color: "f7e101"
  description: ""
- name: "Don't Merge"
  color: "f7e101"
  description: ""
- name: "Don't Review"
  color: "f7e101"
  description: ""
- name: "GZ merge"
  color: "f7e101"
  description: ""
- name: "Hotfix"
  color: "f7e101"
  description: ""
- name: "Marketplace"
  color: "f7e101"
  description: ""
- name: "Pending QA"
  color: "f7e101"
  description: ""
- name: "Planning-Guest"
  color: "f7e101"
  description: ""
- name: "Platform Group"
  color: "f7e101"
  description: ""
- name: "Registry"
  color: "f7e101"
  description: ""
- name: "release 3.55.0"
  color: "f7e101"
  description: ""
- name: "Reviewer Needed"
  color: "f7e101"
  description: ""
- name: "ruby"
  color: "f7e101"
  description: ""
- name: "Second Reviewer Needed"
  color: "f7e101"
  description: ""
- name: "XONetworking Pod PR Needed"
  color: "f7e101"
  description: ""