default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :custom_lane_shared_gp do
    UI.message "🟢 custom lane from gp shared fastlane"
    app_store_connect_authentication
    shared_gp
  end

  desc "Description of what the lane does"
  lane :common_appstore do
    UI.message "🟢 appstore lane from gp shared fastlane"
    fastfile_appstore_lane
  end

  desc "Description of what the lane does"
  lane :certificates_gp do
    UI.message "🟢 certificates lane from gp shared fastlane"
    certificates_lane
  end
  
end