default_platform(:ios)

# import '../fastlane-tk/Fastfile'

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane_shared_gp do
    UI.message "🟢 custom lane from gp shared fastlane"
    shared_gp
  end
end