default_platform(:ios)

import_from_git(url: "git@github.com:mikelabraca/shared-fastlane.git",
                path: "fastlane-common/Fastfile",
                branch: "feature/testing-local-imports")

# import '/Users/miguel/Desktop/fastlane-test/shared-fastlane/fastlane-common/Fastfile'

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane_shared_tk do
    # add actions here: https://docs.fastlane.tools/actions
    UI.message "🟢 custom lane from tk shared fastlane"
    shared_tk
  end
end