default_platform(:ios)

import '../fastlane-tk/Fastfile'

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane_shared_tk do
    # add actions here: https://docs.fastlane.tools/actions
    UI.message "🟢 custom lane from tk shared fastlane"
    shared_tk
  end
end