default_platform(:ios)

if ENV["local_fastlane"] == 'true'
  import "#{ENV['local_fastlane_dir']}/fastlane-common/Fastfile"
else 
  import_from_git(url: "git@github.com:mikelabraca/shared-fastlane.git",
                  path: "fastlane-common/Fastfile",
                  branch: ENV["fastlane_remote_branch"])
end

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane_shared_tk do
    UI.message "🟢 custom lane from tk shared fastlane"
    shared_tk
  end
end